### ISSUE TITLE
moz status

### ISSUE THREAD

**Issue by svgeesus** [w3c/media-web-roadmap#9]
There is a way to indicate chrome, webkit and edge status. A way to indicate mozilla/gecko status would also be desirable.

**Comment by dontcallmedom** [comment]
in practice, the Chrome platform status is often a reliable enough source of information for gecko implementation.

[Mozilla's platform status system](https://platform-status.mozilla.org/) is [based on markdown files](https://github.com/mozilla/platform-status/tree/master/features) which is more painful to parse in the current toolchain, so adding direct support for it would only be justified if it brought lots of new or more accurate information from my perspective.
